# Use the official Python image as base
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app/

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app files into the container
COPY . /app/

# Expose port 5000 to the outside world
EXPOSE 5000

# Command to run Gunicorn and serve the Flask app
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app:app"]
